nanalysis/nmrfx

.github/workflows/main.yml

Update workflow to use gihub runner (ubuntu with zulu jdk) instead of Nanalysis' private worker.

test workflow on github runner

---

nmrfx-processor-gui/src/main/java/module-info.java
nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/ChartProcessor.java
nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/FXMLController.java
nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/RefManager.java
nmrfx-processor/src/main/java/org/nmrfx/processor/datasets/vendor/NMRData.java
nmrfx-processor/src/main/java/org/nmrfx/processor/datasets/vendor/RS2DData.java
nmrfx-processor/src/main/java/org/nmrfx/processor/processing/Processor.java
nmrfx-processor/src/test/java/org/nmrfx/processor/datasets/vendor/RS2DDataTest.java

small improvements, could still be better.

Nmr 4668 simpler spinitexport

---

nmrfx-bom/pom.xml
nmrfx-core/pom.xml
nmrfx-jmx-connector/src/main/java/org/nmrfx/jmx/NotificationType.java
nmrfx-jmx-connector/src/main/java/org/nmrfx/jmx/mbeans/Analyst.java
nmrfx-processor/src/main/java/module-info.java
nmrfx-processor/src/main/java/org/nmrfx/processor/events/DatasetSavedEvent.java
nmrfx-processor/src/main/java/org/nmrfx/processor/processing/Processor.java

includes https://github.com/nanalysis/nmrfx/pull/61 and https://github.com/nanalysis/nmrfx/pull/59 but needed to merge master, otherwise it would miss script generation from spinit and break interactions from there.
Only to be merged once the two others PR are.

Nmr 4682 notification on data save

---

nmrfx-core/src/main/java/org/nmrfx/math/units/UnitFactory.java

UnitFactory was removed by https://github.com/nanalysis/nmrfx/pull/65 but is actually used by python code.

revert UnitFactory, called by python code.

---

nmrfx-processor/src/main/java/org/nmrfx/processor/datasets/vendor/rs2d/PhaseMod.java
nmrfx-processor/src/main/java/org/nmrfx/processor/datasets/vendor/rs2d/RS2DData.java
nmrfx-processor/src/main/java/org/nmrfx/processor/processing/ProcessingException.java
nmrfx-processor/src/main/java/org/nmrfx/processor/processing/Processor.java

use PHASE_MOD when possible, fallback on ACQUISITION_MODE when not defined (for older data)

Nmr 4883 use phase mod param

---

.github/workflows/actions-delete-build.sh
.github/workflows/actions-publish-build.sh
.github/workflows/build.yml
.github/workflows/cleanup.yml

NMR-4963: publish builds to nanalysis's sharepoint

---

.github/workflows/build.yml

fix for which module is published

NMR-4963: we were publishing the wrong module

---

nmrfx-analyst-gui/pom.xml
nmrfx-analyst/pom.xml
nmrfx-bom/pom.xml
nmrfx-core/pom.xml
nmrfx-jmx-connector/pom.xml
nmrfx-launchers/pom.xml
nmrfx-plugin-api/pom.xml
nmrfx-processor-gui/pom.xml
nmrfx-processor/pom.xml
nmrfx-structure/pom.xml
nmrfx-utils/pom.xml
pom.xml

I didn't change nmrfx-private or ringnmr.

version 11.2.4-SNAPSHOT

---

nmrfx-processor/src/main/java/org/nmrfx/processor/datasets/vendor/nmrview/NMRViewData.java

Sonar indicated that `parMap` was always null, thus all if/else branching testing that were useless.
I also removed unused attributes and methods.

Simplify NMRViewData, remove dead code.

---

docs/release.md

@brucejohnson please tell me whether this is clear enough or if steps are missing or should be more detailed.

Add release doc

---

nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/peaks/NOETableController.java
nmrfx-analyst/src/main/java/org/nmrfx/analyst/dataops/Align.java
nmrfx-core/src/main/java/org/nmrfx/chemistry/Atom.java
nmrfx-core/src/main/java/org/nmrfx/chemistry/SpatialSetGroup.java
nmrfx-core/src/main/java/org/nmrfx/chemistry/constraints/Noe.java
nmrfx-core/src/main/java/org/nmrfx/chemistry/io/NMRStarReader.java
nmrfx-structure/src/main/java/org/nmrfx/structure/chemistry/Molecule.java
nmrfx-structure/src/main/java/org/nmrfx/structure/noe/NOEAssign.java
nmrfx-structure/src/main/java/org/nmrfx/structure/noe/NOECalibrator.java

- removed 3 useless loops in SpatialSetGroup, Align and Molecule
- replaced System.out with log in all files affected by the above point's changes

Nmr 5107 remove useless loops

---

nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/tools/MinerController.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/tools/ScanTable.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/tools/ScannerTool.java
nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/ProcessorController.java
nmrfx-processor/src/main/java/org/nmrfx/processor/processing/ProcessorAvailableStatusListener.java

~~If processor was busy, logged a message instead of trying to load the row.~~
Disabled scanner table and buttons if the processor is in use.

NMR-5315: if processor is in use, dont load the scan table row

---

.github/workflows/build.yml
.github/workflows/cleanup.yml
nmrfx-analyst-gui/pom.xml
nmrfx-analyst/pom.xml
nmrfx-bom/pom.xml
nmrfx-core/pom.xml
nmrfx-jmx-connector/pom.xml
nmrfx-launchers/pom.xml
nmrfx-plugin-api/pom.xml
nmrfx-processor-gui/pom.xml
nmrfx-processor/pom.xml
nmrfx-structure/pom.xml
nmrfx-utils/pom.xml
pom.xml

Nmr 5228 java17

---

nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/events/DataFormatHandlerUtil.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/events/FilesDataFormatHandler.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/events/MoleculeDataFormatHandler.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/events/PlainTextDataFormatHandler.java
nmrfx-core/src/main/java/org/nmrfx/chemistry/io/SDFile.java
nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/events/DataFormatEventHandler.java
nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/spectra/DragBindings.java
nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/spectra/KeyBindings.java
nmrfx-processor/src/main/java/org/nmrfx/processor/datasets/vendor/NMRDataUtil.java

Molecule files can be dragged on to a canvas.
Highlighted molecule file text can be dragged on to a canvas.
Note: pr based off of NMR-4505, since modifying DataHandlers added in that class

NMR-4517 allow drag drop for molecules

---

nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/AnalystApp.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/ProjectMenuActions.java
nmrfx-core/src/main/java/org/nmrfx/project/ProjectBase.java
nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/FXMLController.java
nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/project/GUIProject.java
nmrfx-processor/src/main/java/org/nmrfx/processor/project/Project.java
nmrfx-structure/src/main/java/org/nmrfx/structure/project/StructureProject.java

Disabled the favorite button if the active project does not have a  project directory set.

Nmr 5675 favoriting dataset without project causes exception

---

nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/MainApp.java

The stages and controllers were not being removed from the stages/controllers lists since the close functionality was not being called. setOnCloseRequest is only triggered by external close events, programmatically closing will not trigger it.

NMR-5729 projects generating too many windows

---

.github/workflows/actions-delete-build.sh

build not deleting, this pr https://github.com/nanalysis/nmrfx/pull/168 was missing a matching change on nmrfx-private. matching pr with https://github.com/nanalysis/nmrfx-private/pull/22

only use valid chars when creating sharepoint foldername

---

nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/PolyChart.java
nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/spectra/ChartBorder.java
nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/spectra/DatasetAttributes.java
nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/spectra/DrawSpectrum.java
nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/spectra/GestureBindings.java
nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/spectra/mousehandlers/MouseBindings.java
nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/spectra/mousehandlers/ViewMouseHandlerHandler.java

based off https://github.com/nanalysis/nmrfx/pull/195

Nmr 5831 improve projection scaling

---

nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/events/FilesDataFormatHandler.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/events/PlainTextDataFormatHandler.java
nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/FXMLController.java
nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/PolyChart.java
nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/SpecAttrWindowController.java
nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/SpectrumStatusBar.java
nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/spectra/DatasetAttributes.java
nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/spectra/DrawSpectrum.java

Note: this pr will likely have significant merge conflicts with NMR-5978

Nmr 5731 drag and drop higher dim onto lower dim datasets

---

nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/FXMLController.java
nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/ProcessorController.java
nmrfx-processor/src/main/java/org/nmrfx/processor/datasets/Dataset.java
nmrfx-processor/src/main/java/org/nmrfx/processor/datasets/vendor/bruker/BrukerData.java
nmrfx-processor/src/main/java/org/nmrfx/processor/datasets/vendor/nmrview/NMRViewData.java
nmrfx-processor/src/main/java/org/nmrfx/processor/processing/Processor.java

The freqDomain array was being set to all true for all datasets when they were loaded

NMR-5951 freq domain not set correctly

---

nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/AnalystApp.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/python/AnalystPythonInterpreter.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/ChartProcessor.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/GUIScripter.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/PropertyManager.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/spectra/WindowIO.java

Extract class to share python interpreter explicitly.

Nmr 6891 extract python interpreter

---

nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/PolyChart.java

Automated rearrange of code for easier reviews later on.
No other changes -> no risk.

NMR-6922: rearrange code (intellij)

---

nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/AnalystApp.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/peaks/LigandScannerController.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/regions/RegionsTable.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/regions/RegionsTableController.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/spectra/SpectrumMenuActions.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/tools/TRACTGUI.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/AxisChangeListener.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/DatasetView.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/FXMLController.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/FXMLControllerManager.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/GUIScripter.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/PeakMenuBar.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/PolyChart.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/PolyChartManager.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/ProcessorController.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/PropertyManager.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/SpectrumStatusBar.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/spectra/SpectrumAdjuster.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/spectra/crosshair/CrossHairs.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/undo/ChartUndoLimits.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/undo/ChartUndoScale.java

Not finished, but if we can already test and merge that, it's better than nothing

Nmr 6922 polychart instance management

---

nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/AttributesController.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/FXMLController.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/GUIScripter.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/PeakPicking.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/PolyChart.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/SpectrumStatusBar.java

A bit less accessible fields. Some remains to be fixed.

Nmr 6922 polychart avoid accessible fields

---

nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/FXMLController.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/PolyChart.java

Replace fields & array with Insets class. Easier to follow when each side has a name instead of an index...
Correspondence with old array indexes:
0 = left
1 = right
2 = bottom
3 = top

Nmr 6922 polychart borders

---

docs/removed-code.md
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/PolyChart.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/spectra/DrawSpectrum.java
nmrfx-utils/src/main/java/org/nmrfx/fxutil/Fx.java

Clean DrawSpectrum, then reuse PolyChartAxis instead of coping axis & mode arrays (and having to maintain them coherent)

Nmr 6922 clean draw spectrum

---

nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/events/FilesDataFormatHandler.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/events/PlainTextDataFormatHandler.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/regions/RegionsTableController.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/tools/MultipletTool.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/AttributesController.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/AxisChangeListener.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/ChartProcessor.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/FXMLController.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/FXMLControllerManager.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/GUIScripter.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/Phaser.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/PolyChart.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/PolyChartManager.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/ProcessorController.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/PropertyManager.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/spectra/DrawSpectrum.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/spectra/GestureBindings.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/spectra/KeyBindings.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/spectra/PeakMenu.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/spectra/SpectrumMenu.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/spectra/crosshair/CrossHairs.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/spectra/mousehandlers/MouseBindings.java

No direct field access anymore for PolyChart.
FXMLController was exposed by 2 different getters. I've kept only the most explicit one.

Nmr 6922 polychart accessors

---

nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/ChartProcessor.java

Rearranging everything was dangerous and we reverted it, but ChartProcessor seems necessary: it had fields mixed with methods in the class body.

NMR-6900: rearrange ChartProcessor

---

nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/FXMLControllerManager.java

This has been removed by mistake while working on FXMLControllerManager.

NMR-6904: notifies AnalystApp when a stage is closed.

---

nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/molecule/SequenceGUI.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/molecule3D/MolCoords.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/molecule3D/MolCylinders.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/molecule3D/MolSceneController.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/molecule3D/MolSpheres.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/molecule3D/Spheres.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/peaks/PeakMenuActions.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/tools/JournalTool.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/tools/PopOverTools.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/tools/RunAboutGUI.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/tools/ScannerTool.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/GUIScripter.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/OperationListCell.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/PeakAttrController.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/PeakMenuBar.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/PeakNavigator.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/PeakPicking.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/PreferencesController.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/ProcessorController.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/PropertyManager.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/SpectrumStatusBar.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/log/Log.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/project/GUIProject.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/spectra/DrawPeaks.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/spectra/KeyBindings.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/spectra/PeakDisplayParameters.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/spectra/PeakListAttributes.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/spectra/SpectrumAdjuster.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/utils/ColorSchemes.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/utils/PeakListUpdater.java

Also renamed mutable fields in lowerCamelCase, renamed immutable fields UPPER_SNAKE_CASE except final fields for mutable object like Random, Map & List where I kept the original lowerCamelCase name.

NMR-7010: review non-final static fields: analyst-gui

---

nmrfx-core/src/main/java/org/nmrfx/chemistry/AtomProperty.java
nmrfx-core/src/test/java/org/nmrfx/chemistry/AtomPropertyTest.java

Use an enum instead of relying on constant declaration order

Clean atomproperty

---

nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/AnalystApp.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/DatasetBrowserController.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/FileMenuActions.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/FXMLController.java

Nmr 6971 datasets toolbar icon should open dataset browser

---

nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/tools/MultipletTool.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/PolyChart.java

Not sure about performance impacts.
Noticed a few places missing null checks, and many places accessing attributesList.get(0) without checking the size first.
In all cases, nothing prevents clearing the list between the list size check and the access...

Nmr 6922 refactor polychart: use getFirstDatasetAttributes() more

---

nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/GUIScripter.java
nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/spectra/PeakListAttributes.java

Peak label types weren't restored from .yaml.

---

docs/dataset.md
docs/nv-file-format.md

A few notes to document the various classes related to loading datasets and their relation.
The plantuml diagram looks like this:

Dataset doc

---

nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/molecule/MoleculeMenuActions.java
nmrfx-core/src/main/java/org/nmrfx/chemistry/MoleculeFactory.java
nmrfx-core/src/main/java/org/nmrfx/chemistry/io/MMcifReader.java
nmrfx-core/src/main/java/org/nmrfx/chemistry/io/Mol2File.java
nmrfx-core/src/main/java/org/nmrfx/chemistry/io/NMRNEFReader.java
nmrfx-core/src/main/java/org/nmrfx/chemistry/io/NMRStarReader.java
nmrfx-core/src/main/java/org/nmrfx/chemistry/io/PDBFile.java
nmrfx-core/src/main/java/org/nmrfx/chemistry/io/PSFFile.java
nmrfx-core/src/main/java/org/nmrfx/chemistry/io/SDFile.java
nmrfx-core/src/main/java/org/nmrfx/chemistry/io/Sequence.java
nmrfx-core/src/test/java/org/nmrfx/chemistry/MoleculeTest.java
nmrfx-core/src/test/java/org/nmrfx/peaks/PeakListTest.java
nmrfx-core/src/test/java/org/nmrfx/structure/chemistry/MMCifFileTest.java
nmrfx-core/src/test/java/org/nmrfx/structure/chemistry/NEFFileTest.java
nmrfx-structure/src/main/java/org/nmrfx/structure/chemistry/Molecule.java
nmrfx-structure/src/main/java/org/nmrfx/structure/project/StructureProject.java

Delay setting active till necessary

Don't store molecule till fully created.

---

.gitignore
nmrfx-analyst/src/main/java/org/nmrfx/processor/math/MatrixND.java
nmrfx-analyst/src/main/java/org/nmrfx/processor/operations/ProcIndirectOp.java
nmrfx-analyst/src/main/resources/pyproc.py

Main places to look at are
`nmrfx-analyst/src/main/java/org/nmrfx/processor/operations/ProcIndirectOp.java`
and the bottom of 
`nmrfx-analyst/src/main/java/org/nmrfx/processor/math/MatrixND.java`
(everything below line 1229).

Process indirect dims
