- nmrfx-bom/pom.xml
- nmrfx-processor/pom.xml
- nmrfx-processor/src/main/java/module-info.java
Separated the dependency import as it's own PR to isolate the import in case it causes errors. This needs to wait for the spelling error to be fixed in the jcamp-parser module-info.java file to be accurate.
> NMR-4493 Import jcamp-parser as dependency.

- nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/AnalystApp.java
- nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/MainApp.java
The alternative would be to specify the formatting locale when calling `String.format(..)`, at least in `Phaser`.
That would be cleaner, especially if we expect to translate the software one day, but the risk of forgetting that in future calls is huge. 
This is also called when creating STAR3 files (peak lists) among others, which I suspect wouldn't work with commas in numbers either.
> NMR-4491: force format locale to avoid comma in formatted numbers

- .github/workflows/cleanup.yml
Cleanup.yml failed on branch delete, as it couldn't find the test-data repository, made the checkout command use the same format as build.yml
> NMR-5222: add permissions to test data submodule to cleanup.yml

- nmrfx-processor/src/main/java/org/nmrfx/processor/datasets/vendor/jcamp/JCAMPData.java
For Echo-AntiEcho and States-tppi, the inverse of whatever was in f1 reverse resulted in the correct spectrum
Switched to check for $SFO1 as sf label first, 
Note: JRES experiment still does not load correctly but it seems to be a result of the test file not having the correct Acquisition Scheme
> Nmr 5326 test 2 d jcamp files from spinit

- nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/FXMLController.java
The undo queue wasn't cleared when new datasets were loaded, so the queue could contain undo elements with the wrong dimensions since the previous dataset might not have had the same dimensions resulting in an out of bounds exceptions.
> NMR-5271: clear undo manager when a new dataset is loaded

- nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/spectra/SpectrumMenuActions.java
- nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/FXMLController.java
- nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/MainApp.java
Can copy and paste into desktop app Word (Office 365) on windows. (Right click after pasting to convert to shape and components can be moved around)
Can copy and paste into Inkscape (tested on Linux)
Note: Copy and paste does not work with online versions of Word (Office 365) which seems to have more limited copy and paste options: (https://support.microsoft.com/en-us/office/copy-and-paste-in-office-for-the-web-682704da-8360-464c-9a26-ff44abf4c4fe#__word_web_app)
> NMR-4506: store svg clipboard content as ByteBuffer

- nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/ChartProcessor.java
- nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/ProcessorController.java
- nmrfx-processor/src/main/java/org/nmrfx/processor/processing/Processor.java
There were two separate issues:
1. On halt, the dataset was not always being closed, and trying to process a new FID would not create a new dataset since there was one already open. (stacktrace in HMBC-COSY.txt)
2. Loading files with different variable names for sw/sf resulted in an exception (stacktrace in hnconus-1H1d.txt)
> Nmr 5448 halting processing can cause exception on next load and process

- .github/workflows/actions-delete-build.sh
(copied from spinlab)
if branch name has a punctuation sign (single apostrophe : ' in my case), build fails.
> Remove punctuations from folder name

- nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/AnalystApp.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/tools/PeakSlider.java
- nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/spectra/KeyBindings.java
There were two sorts of issues:
1. When the peak slider tool was closed, the listeners weren't removed so setActivePeaks, which was drawing the peaks without selection, would end up be called after the selected peaks were drawn.
- fix -> remove listeners
The setActivePeaks method was drawing the peaks without selection so if the peak slider was open, selecting a multiplet arm would not show up as selected, even though it was selected and the popup multiplet tool would delete it.
- fix -> Dont call draw peaks in setActivePeaks method.
> Nmr 5543 cannot select peaks after peak slider tool opened

- nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/events/FilesDataFormatHandler.java
- nmrfx-processor/src/main/java/org/nmrfx/processor/datasets/vendor/NMRDataUtil.java
JCAMP processed data, RS2D unprocessed and processed data, Bruker processed data and Jeol jdf files (only tested with the two from the test files) can now be drag and dropped
> Nmr 5730 rs2 d jcamp datasets cant drag and drop

- nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/tools/SimplePeakRegionTool.java
- nmrfx-analyst/src/test/java/org/nmrfx/analyst/peaks/AnalyzerTest.java
- nmrfx-core/src/main/java/org/nmrfx/datasets/DatasetBase.java
- nmrfx-core/src/main/java/org/nmrfx/datasets/DatasetFactory.java
- nmrfx-core/src/main/java/org/nmrfx/datasets/DatasetParameterFile.java
- nmrfx-core/src/main/java/org/nmrfx/project/ProjectBase.java
- nmrfx-processor/src/main/java/org/nmrfx/processor/datasets/Dataset.java
- nmrfx-processor/src/main/java/org/nmrfx/processor/datasets/vendor/jcamp/JCAMPData.java
- pom.xml
Spinlab datasets were saving as nvlnk files but weren't loading since only Bruker nvlnk files were set up.
JCAMP datasets were not saving since they didn't have a file set.
Also loaded the regions for the nvlnk files which were ignored previously, no way to store the norm with the nvlnk so I recalculated it
Note: based pr off https://github.com/nanalysis/nmrfx/pull/184 so that I can used the same norm calculations when loading the integrals.
> Nmr 5707 jcamp spinlab datasets not saved in projects

- nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/DatasetBrowserController.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/events/FilesDataFormatHandler.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/events/PlainTextDataFormatHandler.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/tools/ScanTable.java
- nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/ChartProperties.java
- nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/FXMLController.java
- nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/PolyChart.java
- nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/PreferencesController.java
- nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/ProcessorController.java
- nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/SpecAttrWindowController.java
- nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/spectra/SpectrumMenu.java
Dragging 1D dataset onto 2D dataset will resize the border and add as a projection to the matching axis.
Projections can be removed through the Extract Slice/ Projection menu.
Projections can be scaled using Attributes -> Slices -> Scale slider which will scale both projections together
Scaling still needs to be improved; changes made in: https://github.com/nanalysis/nmrfx/pull/196
This pr does not cover the case of what should happen if a user drags a 2D dataset onto a 1D dataset (Jira issue made: NMR-5731)
> Nmr 5803 improve 1 d projection display

- nmrfx-bom/pom.xml
- nmrfx-processor/src/main/java/org/nmrfx/processor/datasets/vendor/rs2d/RS2DData.java
Header file contents for STATE param set from NMRFx
Note: this pr based off NMR-5917 because of update to spinlab-dataset
> NMR-5935: set the param STATE in the header when saving RS2D dataset

- nmrfx-core/src/main/java/org/nmrfx/datasets/DatasetBase.java
- nmrfx-core/src/main/java/org/nmrfx/math/VecBase.java
- nmrfx-core/src/main/java/org/nmrfx/project/ProjectBase.java
- nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/MainApp.java
- nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/PeakPicking.java
- nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/PolyChart.java
- nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/SpectrumStatusBar.java
- nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/spectra/DatasetAttributes.java
- nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/spectra/DrawSpectrum.java
- nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/spectra/GestureBindings.java
- nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/spectra/SpectrumMenu.java
- nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/spectra/mousehandlers/MouseBindings.java
- nmrfx-processor/src/main/java/org/nmrfx/processor/datasets/Dataset.java
projections with complex datasets had 2 issues, the empty real vec was being read instead of real values from complex vec, and only half the file was read due to real indices being passed instead of raw to readDatasetFromFile
Also fixed exception that occurs if a user switched from 2D view to 1D view while projections are displayed
> NMR-5803 projections with JCAMP RS2D datasets

- nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/tools/ScanTable.java
- nmrfx-bom/pom.xml
- nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/DatasetsController.java
- nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/PolyChart.java
- nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/controls/FileTableItem.java
- nmrfx-processor/src/main/java/org/nmrfx/processor/datasets/vendor/NMRDataUtil.java
- nmrfx-processor/src/main/java/org/nmrfx/processor/datasets/vendor/rs2d/RS2DData.java
The drawlist was being set based on the number of frequency dimensions. For T1 experiments with .nv datasets, this value is set as 1 (value set from the .par file), for other types of datasets this value is set to the number of dimensions, (since they don't have a par file) so a RS2D t1 has this value set as 2. Since we only differentiate between 2D and pseudo2D by guessing from the number of scans, it would be difficult to set the number of frequency dimensions correctly. Using the chart display type property seems to work for both the .nv files and the JCAMP and RS2D datasets.
> NMR-5841 scanner tool not working with JCAMP RS2D

- nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/ContentController.java
In order for Contents dataset view to be always up to date, it listens to the active projects dataset map. This map is updated from one of the Processor Task threads which results in the GUI getting updated from the non application thread. Moving the update code into Platform.runLater removes the warning.
> NMR 6155 javafx thread exception processing with Contents

- nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/spectra/GestureBindings.java
Change to scale with scroll wheel instead of ctrl+scroll, assume mac use natural scrolling and windows and linux use traditional scrolling, for 1D left border will change vertical offset instead of zoom
Slightly different from Jira issue 
-> double click will not zoom out (@brucejohnson requested this not be implemented)
-> Scale will adjust on scroll instead of ctrl + scroll (does the same thing whether above or below the baseline)
> NMR-4777 mutalize mousebind action between spinit and NMRF

- nmrfx-utils/src/main/java/org/nmrfx/chart/Axis.java
- nmrfx-utils/src/main/java/org/nmrfx/graphicsio/PDFGraphicsContext.java
- nmrfx-utils/src/main/java/org/nmrfx/graphicsio/SVGGraphicsContext.java
Added fine gridlines and made them dashed. The dash is currently set to 1 but can be adjusted if its too fine of a dash
Before and after 
Export to pdf
[test.pdf](https://github.com/nanalysis/nmrfx/files/10768308/test.pdf)
Export to png
Export to svg
> NMR-6392: add minor tick gridlines and make all gridlines dashed

- nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/tools/ScanTable.java
Since we switched to not closing the datasets by default when processing, this caused an issue in the scan table where the dataset files were never created, so when the Scan Table went to load the first dataset after processing the directory, there were no files created.  Setting keepDatasetOpen to false will save the dataset to file after each row of the table is processed
> NMR-6351_processing_scan_directory_throws_illegal_argument_exception

- nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/PolyChart.java
- nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/SpectrumStatusBar.java
- nmrfx-processor/src/main/java/org/nmrfx/processor/processing/Processor.java
PolyChart.setDataset was setting disDimProp before setting the dataset. disDimProp has a listener that gets the Dataset from PolyChart, so it was retrieving the old dataset which had already been closed/dataFile set to null.
Moved code setting freq dimensions outside of if statement, this seems to allow the right number of spectrums to display when switching to stack plot mode for experiments we have processed
> NMR-6449 processing in stack display mode causes NPE

- nmrfx-processor-gui/src/main/java/org/nmrfx/processor/gui/ChartProcessor.java
- nmrfx-processor/src/main/java/org/nmrfx/processor/datasets/vendor/NMRDataUtil.java
The nucleus was always guessed from the function https://github.com/nanalysis/nmrfx/blob/8f1b8916ba60edcfaee51f4cc7e95c2fe765a158/nmrfx-core/src/main/java/org/nmrfx/datasets/Nuclei.java#L320
This function always guessed 1H since it only ever received frequency array of length 1. Instead changed FID w/ops datasets to set the nucleus with the transmit nucleus (How the nucleus is set for the spectrum datasets). Also updated another nuclei guessing function to check the benchtop frequencies as well. 
https://github.com/nanalysis/nmrfx/blob/7dd679447ce3984bee9581d85087bf14db854924/nmrfx-processor/src/main/java/org/nmrfx/processor/datasets/vendor/NMRDataUtil.java#L256
This function is used as a backup when retrieving the transmit nucleus for JCAMPData and BrukerData. The other NMRData do not …
> NMR-6451 xaxis always defaults to 1H when displaying FIDS with OPs

- nmrfx-structure/src/test/java/org/nmrfx/structure/chemistry/energy/PyStructureTest.java
- nmrfx-structure/src/test/python/testrnalinks.py
Raise energy threshold for passing
Random structures could fail with previous structures
> NMR-6498-py-structure-test-fails-sometimes

- nmrfx-processor/src/main/java/org/nmrfx/processor/datasets/vendor/rs2d/RS2DData.java
ACQUISITION_MATRIX_DIMENSION could have a different size than the number of points actually present (processed files + poorly converted jcamp files)
> always use MATRIX_DIMENSION when opening rs2d data

- nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/AnalystApp.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/DatasetBrowserController.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/FileMenuActions.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/PeakGeneratorGUI.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/ViewMenuItems.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/molecule/MoleculeUtils.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/peaks/PeakAssignTool.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/peaks/PeakAtomPicker.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/peaks/PeakListsTableController.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/peaks/PeakMenuActions.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/peaks/PeakTableController.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/spectra/SpectrumMenuActions.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/tools/JournalTool.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/tools/PeakSlider.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/tools/RunAboutGUI.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/tools/ScanTable.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/DatasetsController.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/FXMLController.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/FXMLControllerManager.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/GUIScripter.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/PeakNavigator.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/PeakPicking.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/PolyChart.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/PreferencesController.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/spectra/PeakDisplayTool.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/spectra/WindowIO.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/tools/PeakLinker.java
- nmrfx-jmx-connector/src/main/java/org/nmrfx/jmx/mbeans/Analyst.java
Trying to progressively reduce FXMLController's responsability.
Moving instance management to a separate FXMLControllerManager.
Classes should be renamed, but at a later time since some plugins reference them.
Most file changes are very simple and only update the calling path.
Main changes that need review are in FXMLController & FXMLControllerManager.
> Nmr 6893 split fxml controller

- nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/PolyChart.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/PolyChartAxes.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/spectra/DatasetAttributes.java
Removed accessors to axis & mode arrays.
PolyChartAxis isn't perfect, but good enough to close this axis parentheses and get back to PolyChart itself.
> Nmr 6922 hide axis arrays

- nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/ChartDrawingLayers.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/FXMLController.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/PolyChart.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/PolyChartManager.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/controls/GridPaneCanvas.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/spectra/DrawPeaks.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/spectra/DrawSpectrum.java
A few direct access to inside canvas remains, but the PR starts to get too big. May be worth an intermediate review.
Goal of this change is to be very clear on what canvas is used to paint what components, show that they are shared, and manage them together as one object. This also removes some cross-references to fxmlcontroller hopefully.
> Nmr 6953 explicit shared canvas

- nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/ChartDrawingLayers.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/FXMLController.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/PolyChart.java
I will not be able to do better without investing more time that what I'm willing to invest for now, so 3 layers will remain exposed.
They are used to compute popover coordinates, add items to the top pane, check if charts are on the same pane, etc.
> NMR-6953: rename remaining accessors

- nmrfx-analyst-gui/src/main/java/org/nmrfx/analyst/gui/ViewMenuItems.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/FXMLController.java
- nmrfx-analyst-gui/src/main/java/org/nmrfx/processor/gui/ProcessorController.java
Note based on: https://github.com/nanalysis/nmrfx/pull/340
The ProcessorController behaves exactly like previous except the new button replaces the View menu option. The other behaviour change here is that the phasing/attributes/contents buttons are affected by whether the processing controller is being viewed, for NMR-6974 we will need to clarify if we still want the processor controller to behave this way (taking priority over other content)
> NMR-6969: add processing top level button

- nmrfx-core/src/main/java/org/nmrfx/chemistry/io/NMRStarReader.java
- nmrfx-core/src/main/java/org/nmrfx/chemistry/io/NMRStarWriter.java
- nmrfx-core/src/main/java/org/nmrfx/project/ProjectBase.java
- nmrfx-core/src/main/java/org/nmrfx/star/STAR3Base.java
- nmrfx-core/src/main/java/org/nmrfx/star/Saveframe.java
Current bahvior:
-saveframes which are not recognized are currently dropped when saving
Preferred behavior:
- saveframes which are not recognized are written unaltered on saving
This pull request:
- Adds a new field in Saveframe which stores the raw text of that saveframe
- Adds a field in ProjectBase which contains a list of saveframes which do not belong to a recognized category
- Writes out raw text of unprocessed saveframes on project write
Notes:
- The raw text is populated during a second pass of the star file (using mark and reset methods of LineNumberReader). If the readAheadLimit parameter for the mark method is too small, the saveframe will not be written. To avoid this, we set the read ahead limit to be the same as the total file size
- At present this only applies to star …
> NMR 7499 Retain unprocessed saveframes

- nmrfx-analyst-gui/src/main/scripts/filter.py
Part of this script is meant to read the file
`target/myFilter.properties`, and extract the classpath.
The file's structure is of the form
`classpath={path-1}:{path-2}:{path-3}:...`.
The previous form of `filter.py` neglected the 1st path in the list (splitting was done at every `:`); this edit fixes that.
> Fixed bug in `nmrfx-analyst-gui/src/main/scripts/filter.py`

- .github/workflows/build.yml
https://github.blog/changelog/2024-09-16-notice-of-upcoming-deprecations-and-changes-in-github-actions-services/
> `actions/checkout` v2 is EOL. Use checkout v4.
